# Generated by Django 4.2.6 on 2023-10-29 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 29, 15, 17, 47, 448989, tzinfo=datetime.timezone.utc)),
        ),
    ]
