# Generated by Django 4.2.6 on 2023-10-29 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 29, 15, 32, 28, 13437, tzinfo=datetime.timezone.utc)),
        ),
    ]
