# Generated by Django 4.2.6 on 2023-11-02 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_comments_active_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='body',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 2, 18, 54, 22, 913004, tzinfo=datetime.timezone.utc)),
        ),
    ]
